[build]
  command = "npm install && npm run build:netlify"
  functions = "functions"

[functions.timeout]
  directory = "functions"
  # Set the default timeout for all functions (in seconds)
  timeout = 60